type ImeAwareKeyEvent = {
  isComposing?: boolean;
  keyCode: number;
  nativeEvent?: { isComposing?: boolean };
};

/**
 * True when this `keydown` was generated by an IME composition step
 * (typing a Japanese reading, confirming with Enter, cancelling with Esc, ...).
 * Callers should bail out so global shortcuts (modal close on Escape,
 * tag commit on Enter, ...) do not steal the keystroke from the IME.
 *
 * - Native `KeyboardEvent` exposes `isComposing` directly; React's synthetic
 *   `KeyboardEvent` exposes it only on `nativeEvent`. The optional chain
 *   handles both.
 * - WebKit (Safari / Tauri WKWebView) fires `compositionend` BEFORE the
 *   keydown that confirms or cancels the IME, so `isComposing` is already
 *   `false` by the time the handler runs. `keyCode === 229` is the deprecated
 *   but only reliable cross-browser fallback for that case.
 */
export const isImeKeyEvent = (e: ImeAwareKeyEvent): boolean => {
  const composing = e.nativeEvent?.isComposing ?? e.isComposing ?? false;
  return composing || e.keyCode === 229;
};
