export type McpSettings = {
  enabled: boolean;
  token: string;
};

export type McpStatus =
  | { kind: "stopped" }
  | { kind: "running"; port: number }
  | { kind: "failed"; error: string };

/**
 * A copy-pasteable setup snippet for one external AI coding tool, generated by
 * the backend so the server name / port / token stay identical to the
 * `mcp.json` snippet. `hint` says where the snippet goes (a terminal vs a named
 * config file); `code` is the full snippet covering every open workspace.
 */
export type McpSetupSnippet = {
  tool: string;
  hint: string;
  code: string;
};
